services:
  confluence:
    image: atlassian/confluence:9.2.10
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS=-Dupm.plugin.upload.enabled=true
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=confluence
    depends_on:
      - postgres
    ports:
      - 8090:8090
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluence
      - POSTGRES_DB=confluence
      # Use UTF-8 locale (avoid "Collation C is not supported" warning)
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8
      - LANG=C.UTF-8
